name: Windows 10 - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup & Run RustDesk
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe" -OutFile "rustdesk.exe"
          ./rustdesk.exe --install
          Start-Sleep -Seconds 10
          ./rustdesk.exe --password test1234
          $id = ./rustdesk.exe --get-id
          Write-Output "=================================="
          Write-Output "RUSTDESK ID: $id"
          Write-Output "RUSTDESK PASSWORD: test1234"
          Write-Output "=================================="
      - name: Keep Alive
        run: |
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
